In [9]:
import pandas as pd

In [20]:
df = pd.read_csv("police_killings.csv", encoding = "latin1")

In [25]:
def extract_data():
    df = pd.read_csv("police_killings.csv", encoding = "latin1")
    return df

df

In [27]:
df.columns

Index(['name', 'age', 'gender', 'raceethnicity', 'month', 'day', 'year',
       'streetaddress', 'city', 'state', 'latitude', 'longitude', 'state_fp',
       'county_fp', 'tract_ce', 'geo_id', 'county_id', 'namelsad',
       'lawenforcementagency', 'cause', 'armed', 'pop', 'share_white',
       'share_black', 'share_hispanic', 'p_income', 'h_income',
       'county_income', 'comp_income', 'county_bucket', 'nat_bucket', 'pov',
       'urate', 'college'],
      dtype='object')

In [28]:
df.info

<bound method DataFrame.info of                    name age  gender    raceethnicity     month  day  year  \
0    A'donte Washington  16    Male            Black  February   23  2015
1        Aaron Rutledge  27    Male            White     April    2  2015
2           Aaron Siler  26    Male            White     March   14  2015
3          Aaron Valdez  25    Male  Hispanic/Latino     March   11  2015
4          Adam Jovicic  29    Male            White     March   19  2015
..                  ...  ..     ...              ...       ...  ...   ...
462  William Chapman II  18    Male            Black     April   22  2015
463    William Dick III  28    Male  Native American     April    4  2015
464       William Poole  52    Male            White     March   16  2015
465   Yuvette Henderson  38  Female            Black  February    3  2015
466       Zaki Shinwary  48    Male          Unknown   January   16  2015

                                 streetaddress          city state  ...  \
0                                 Clearview Ln     Millbrook    AL  ...
1                       300 block Iris Park Dr     Pineville    LA  ...
2                         22nd Ave and 56th St       Kenosha    WI  ...
3                            3000 Seminole Ave    South Gate    CA  ...
4                               364 Hiwood Ave  Munroe Falls    OH  ...
..                                         ...           ...   ...  ...
462                        1098 Frederick Blvd    Portsmouth    VA  ...
463             Bureau of Indian Affairs Rd 66      Tonasket    WA  ...
464                             130 Wedowee Ln        Gaston    NC  ...
465                             3800 Hollis St       Oakland    CA  ...
466  Lake Arrowhead Ave and Great Salt Lake Dr       Fremont    CA  ...

     share_hispanic  p_income  h_income  county_income  comp_income  \
0               5.6     28375   51367.0          54766     0.937936
1               0.5     14678   27972.0          40930     0.683411
2              16.8     25286   45365.0          54930     0.825869
3              98.8     17194   48295.0          55909     0.863814
4               1.7     33954   68785.0          49669     1.384868
..              ...       ...       ...            ...          ...
462               0     25262   27418.0          46166     0.593900
463            20.2     18470   35608.0          40368     0.882085
464             0.3     21175   38200.0          42017     0.909156
465            37.1     26971   63052.0          72112     0.874362
466            12.3     33590   88940.0          72112     1.233359

     county_bucket  nat_bucket   pov     urate   college
0              3.0         3.0  14.1  0.097686  0.168510
1              2.0         1.0  28.8  0.065724  0.111402
2              2.0         3.0  14.6  0.166293  0.147312
3              3.0         3.0  11.7  0.124827  0.050133
4              5.0         4.0   1.9  0.063550  0.403954
..             ...         ...   ...       ...       ...
462            1.0         1.0  35.2  0.152047  0.120553
463            1.0         2.0  27.3  0.133650  0.174525
464            2.0         2.0  28.5  0.256150  0.072764
465            2.0         4.0  23.9  0.069601  0.396476
466            4.0         5.0   6.1  0.080912  0.435773

[467 rows x 34 columns]>

In [29]:
df["gender"]

0        Male
1        Male
2        Male
3        Male
4        Male
        ...
462      Male
463      Male
464      Male
465    Female
466      Male
Name: gender, Length: 467, dtype: object

In [30]:
df["gender"].unique()

array(['Male', 'Female'], dtype=object)

In [39]:
df

,name,age,gender,raceethnicity,month,day,year,streetaddress,city,state,...,share_hispanic,p_income,h_income,county_income,comp_income,county_bucket,nat_bucket,pov,urate,college
0,A'donte Washington,16,Male,Black,February,23,2015,Clearview Ln,Millbrook,AL,...,5.6,28375,51367.0,54766,0.937936,3.0,3.0,14.1,0.097686,0.168510
1,Aaron Rutledge,27,Male,White,April,2,2015,300 block Iris Park Dr,Pineville,LA,...,0.5,14678,27972.0,40930,0.683411,2.0,1.0,28.8,0.065724,0.111402
2,Aaron Siler,26,Male,White,March,14,2015,22nd Ave and 56th St,Kenosha,WI,...,16.8,25286,45365.0,54930,0.825869,2.0,3.0,14.6,0.166293,0.147312
3,Aaron Valdez,25,Male,Hispanic/Latino,March,11,2015,3000 Seminole Ave,South Gate,CA,...,98.8,17194,48295.0,55909,0.863814,3.0,3.0,11.7,0.124827,0.050133
4,Adam Jovicic,29,Male,White,March,19,2015,364 Hiwood Ave,Munroe Falls,OH,...,1.7,33954,68785.0,49669,1.384868,5.0,4.0,1.9,0.063550,0.403954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,William Chapman II,18,Male,Black,April,22,2015,1098 Frederick Blvd,Portsmouth,VA,...,0,25262,27418.0,46166,0.593900,1.0,1.0,35.2,0.152047,0.120553
463,William Dick III,28,Male,Native American,April,4,2015,Bureau of Indian Affairs Rd 66,Tonasket,WA,...,20.2,18470,35608.0,40368,0.882085,1.0,2.0,27.3,0.133650,0.174525
464,William Poole,52,Male,White,March,16,2015,130 Wedowee Ln,Gaston,NC,...,0.3,21175,38200.0,42017,0.909156,2.0,2.0,28.5,0.256150,0.072764
465,Yuvette Henderson,38,Female,Black,February,3,2015,3800 Hollis St,Oakland,CA,...,37.1,26971,63052.0,72112,0.874362,2.0,4.0,23.9,0.069601,0.396476
466,Zaki Shinwary,48,Male,Unknown,January,16,2015,Lake Arrowhead Ave and Great Salt Lake Dr,Fremont,CA,...,12.3,33590,88940.0,72112,1.233359,4.0,5.0,6.1,0.080912,0.435773

In [37]:
print(df.columns)

Index(['name', 'age', 'gender', 'raceethnicity', 'month', 'day', 'year',
       'streetaddress', 'city', 'state', 'latitude', 'longitude', 'state_fp',
       'county_fp', 'tract_ce', 'geo_id', 'county_id', 'namelsad',
       'lawenforcementagency', 'cause', 'armed', 'pop', 'share_white',
       'share_black', 'share_hispanic', 'p_income', 'h_income',
       'county_income', 'comp_income', 'county_bucket', 'nat_bucket', 'pov',
       'urate', 'college'],
      dtype='object')

In [42]:
def transform_data(df):

    df.columns = df.columns.str.replace("_", " ")

    df = df.rename(columns={
        "raceethnicity": "race ethnicity",
        "streetaddress": "street address",
        "lawenforcementagency": "law enforcement agency"
    })

    df.columns = df.columns.str.title()

    return df

In [43]:
df

,name,age,gender,raceethnicity,month,day,year,streetaddress,city,state,...,share_hispanic,p_income,h_income,county_income,comp_income,county_bucket,nat_bucket,pov,urate,college
0,A'donte Washington,16,Male,Black,February,23,2015,Clearview Ln,Millbrook,AL,...,5.6,28375,51367.0,54766,0.937936,3.0,3.0,14.1,0.097686,0.168510
1,Aaron Rutledge,27,Male,White,April,2,2015,300 block Iris Park Dr,Pineville,LA,...,0.5,14678,27972.0,40930,0.683411,2.0,1.0,28.8,0.065724,0.111402
2,Aaron Siler,26,Male,White,March,14,2015,22nd Ave and 56th St,Kenosha,WI,...,16.8,25286,45365.0,54930,0.825869,2.0,3.0,14.6,0.166293,0.147312
3,Aaron Valdez,25,Male,Hispanic/Latino,March,11,2015,3000 Seminole Ave,South Gate,CA,...,98.8,17194,48295.0,55909,0.863814,3.0,3.0,11.7,0.124827,0.050133
4,Adam Jovicic,29,Male,White,March,19,2015,364 Hiwood Ave,Munroe Falls,OH,...,1.7,33954,68785.0,49669,1.384868,5.0,4.0,1.9,0.063550,0.403954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,William Chapman II,18,Male,Black,April,22,2015,1098 Frederick Blvd,Portsmouth,VA,...,0,25262,27418.0,46166,0.593900,1.0,1.0,35.2,0.152047,0.120553
463,William Dick III,28,Male,Native American,April,4,2015,Bureau of Indian Affairs Rd 66,Tonasket,WA,...,20.2,18470,35608.0,40368,0.882085,1.0,2.0,27.3,0.133650,0.174525
464,William Poole,52,Male,White,March,16,2015,130 Wedowee Ln,Gaston,NC,...,0.3,21175,38200.0,42017,0.909156,2.0,2.0,28.5,0.256150,0.072764
465,Yuvette Henderson,38,Female,Black,February,3,2015,3800 Hollis St,Oakland,CA,...,37.1,26971,63052.0,72112,0.874362,2.0,4.0,23.9,0.069601,0.396476
466,Zaki Shinwary,48,Male,Unknown,January,16,2015,Lake Arrowhead Ave and Great Salt Lake Dr,Fremont,CA,...,12.3,33590,88940.0,72112,1.233359,4.0,5.0,6.1,0.080912,0.435773

In [44]:
df = extract_data()

df = transform_data(df)

In [45]:
df

,Name,Age,Gender,Race Ethnicity,Month,Day,Year,Street Address,City,State,...,Share Hispanic,P Income,H Income,County Income,Comp Income,County Bucket,Nat Bucket,Pov,Urate,College
0,A'donte Washington,16,Male,Black,February,23,2015,Clearview Ln,Millbrook,AL,...,5.6,28375,51367.0,54766,0.937936,3.0,3.0,14.1,0.097686,0.168510
1,Aaron Rutledge,27,Male,White,April,2,2015,300 block Iris Park Dr,Pineville,LA,...,0.5,14678,27972.0,40930,0.683411,2.0,1.0,28.8,0.065724,0.111402
2,Aaron Siler,26,Male,White,March,14,2015,22nd Ave and 56th St,Kenosha,WI,...,16.8,25286,45365.0,54930,0.825869,2.0,3.0,14.6,0.166293,0.147312
3,Aaron Valdez,25,Male,Hispanic/Latino,March,11,2015,3000 Seminole Ave,South Gate,CA,...,98.8,17194,48295.0,55909,0.863814,3.0,3.0,11.7,0.124827,0.050133
4,Adam Jovicic,29,Male,White,March,19,2015,364 Hiwood Ave,Munroe Falls,OH,...,1.7,33954,68785.0,49669,1.384868,5.0,4.0,1.9,0.063550,0.403954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,William Chapman II,18,Male,Black,April,22,2015,1098 Frederick Blvd,Portsmouth,VA,...,0,25262,27418.0,46166,0.593900,1.0,1.0,35.2,0.152047,0.120553
463,William Dick III,28,Male,Native American,April,4,2015,Bureau of Indian Affairs Rd 66,Tonasket,WA,...,20.2,18470,35608.0,40368,0.882085,1.0,2.0,27.3,0.133650,0.174525
464,William Poole,52,Male,White,March,16,2015,130 Wedowee Ln,Gaston,NC,...,0.3,21175,38200.0,42017,0.909156,2.0,2.0,28.5,0.256150,0.072764
465,Yuvette Henderson,38,Female,Black,February,3,2015,3800 Hollis St,Oakland,CA,...,37.1,26971,63052.0,72112,0.874362,2.0,4.0,23.9,0.069601,0.396476
466,Zaki Shinwary,48,Male,Unknown,January,16,2015,Lake Arrowhead Ave and Great Salt Lake Dr,Fremont,CA,...,12.3,33590,88940.0,72112,1.233359,4.0,5.0,6.1,0.080912,0.435773

In [48]:
df["State"].unique()

array(['AL', 'LA', 'WI', 'CA', 'OH', 'AZ', 'TX', 'MI', 'IN', 'TN', 'GA',
       'VA', 'NE', 'KS', 'OK', 'OR', 'NH', 'FL', 'MA', 'PA', 'WA', 'AR',
       'IA', 'NC', 'NM', 'DC', 'ID', 'CO', 'HI', 'KY', 'SC', 'WV', 'UT',
       'MO', 'MD', 'NY', 'NJ', 'IL', 'CT', 'MS', 'NV', 'MT', 'AK', 'MN',
       'ME', 'DE', 'WY'], dtype=object)

In [49]:
state_map = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "DC": "District of Columbia",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
}

In [53]:
df["State"] = df["State"].map(state_map).fillna(df["State"])

In [54]:
def transform_data(df):
    df["State"] = df["State"].map(state_map).fillna(df["State"])
    return df

In [55]:
df

,Name,Age,Gender,Race Ethnicity,Month,Day,Year,Street Address,City,State,...,Share Hispanic,P Income,H Income,County Income,Comp Income,County Bucket,Nat Bucket,Pov,Urate,College
0,A'donte Washington,16,Male,Black,February,23,2015,Clearview Ln,Millbrook,Alabama,...,5.6,28375,51367.0,54766,0.937936,3.0,3.0,14.1,0.097686,0.168510
1,Aaron Rutledge,27,Male,White,April,2,2015,300 block Iris Park Dr,Pineville,Louisiana,...,0.5,14678,27972.0,40930,0.683411,2.0,1.0,28.8,0.065724,0.111402
2,Aaron Siler,26,Male,White,March,14,2015,22nd Ave and 56th St,Kenosha,Wisconsin,...,16.8,25286,45365.0,54930,0.825869,2.0,3.0,14.6,0.166293,0.147312
3,Aaron Valdez,25,Male,Hispanic/Latino,March,11,2015,3000 Seminole Ave,South Gate,California,...,98.8,17194,48295.0,55909,0.863814,3.0,3.0,11.7,0.124827,0.050133
4,Adam Jovicic,29,Male,White,March,19,2015,364 Hiwood Ave,Munroe Falls,Ohio,...,1.7,33954,68785.0,49669,1.384868,5.0,4.0,1.9,0.063550,0.403954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,William Chapman II,18,Male,Black,April,22,2015,1098 Frederick Blvd,Portsmouth,Virginia,...,0,25262,27418.0,46166,0.593900,1.0,1.0,35.2,0.152047,0.120553
463,William Dick III,28,Male,Native American,April,4,2015,Bureau of Indian Affairs Rd 66,Tonasket,Washington,...,20.2,18470,35608.0,40368,0.882085,1.0,2.0,27.3,0.133650,0.174525
464,William Poole,52,Male,White,March,16,2015,130 Wedowee Ln,Gaston,North Carolina,...,0.3,21175,38200.0,42017,0.909156,2.0,2.0,28.5,0.256150,0.072764
465,Yuvette Henderson,38,Female,Black,February,3,2015,3800 Hollis St,Oakland,California,...,37.1,26971,63052.0,72112,0.874362,2.0,4.0,23.9,0.069601,0.396476
466,Zaki Shinwary,48,Male,Unknown,January,16,2015,Lake Arrowhead Ave and Great Salt Lake Dr,Fremont,California,...,12.3,33590,88940.0,72112,1.233359,4.0,5.0,6.1,0.080912,0.435773

In [61]:
def load_data(df):
    df.to_csv("cleaned_police_killings.csv", index=False)

In [ ]:
df.to_csv( r"C:\Users\userlab\Desktop\peju_python_flow\cleaned_police_killings.csv", index=False)