In [ ]:
#dataset 2
#def extract_data():
    #pass
#def transform_data():
    #pass
#def load_data():
    #pass

In [7]:
import pandas as pd

In [9]:
df = pd.read_csv("products-10000.csv")

In [10]:
df

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Smart Fan Iron Cooker Go Wireless Portable,Catch enough role nearly.,Herman Ltd,Kids' Clothing,585,USD,194,3968600833473,Cornsilk,5x7 in,limited_stock,54
1,2,Fan,All movement yeah tax me.,"Braun, King and Rollins",Grooming Tools,992,USD,724,191126950284,Bisque,S,discontinued,49
2,3,Smart Speakerphone Charger Eco Plus Clean,Quickly inside pull line lay start.,Peck-Coleman,Fishing & Hunting,940,USD,769,7569143820621,Blue,Extra Large,pre_order,42
3,4,Premium Grill Trimmer Portable,Lawyer one than fire.,Hines Ltd,Skincare,324,USD,93,2705140928037,Ivory,50x70 cm,out_of_stock,93
4,5,Keyboard Freezer,Remain Congress blood plan voice.,"Spence, Webster and Orr",Laptops & Computers,908,USD,614,9830391008108,FloralWhite,10x10 cm,discontinued,91
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,Powerbank,Yeah none boy fund city decision.,Castaneda-Harrison,Books & Stationery,567,USD,27,6519003997216,Cyan,Medium,pre_order,7
9996,9997,Rechargeable Lamp Scanner Vacuum,Appear country enter there pull thing computer.,Knapp-Key,Cycling,300,USD,177,4707959228979,MintCream,Large,limited_stock,55
9997,9998,Heater,Owner plan approach soldier church little little.,"Meyer, Case and Mills",Fitness Equipment,399,USD,996,5286509915488,LightGray,Large,pre_order,37
9998,9999,Rechargeable Headphones Stove,Base account partner probably.,Jones-Bell,Kitchen Appliances,45,USD,274,3702651384368,SlateBlue,12x18 in,in_stock,52
9999,10000,Clean Charger Treadmill,Return reflect truth tell scientist season.,Davis LLC,Sports & Outdoors,31,USD,46,8879838276060,Ivory,Medium,backorder,70

In [8]:
df["Size"]

0            5x7 in
1                 S
2       Extra Large
3          50x70 cm
4          10x10 cm
           ...
9995         Medium
9996          Large
9997          Large
9998       12x18 in
9999         Medium
Name: Size, Length: 10000, dtype: object

In [11]:
# Extract: read the dataset
def extract_data():
    df = pd.read_csv("products-10000.csv")
    return df

In [12]:
df.head(10)

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Smart Fan Iron Cooker Go Wireless Portable,Catch enough role nearly.,Herman Ltd,Kids' Clothing,585,USD,194,3968600833473,Cornsilk,5x7 in,limited_stock,54
1,2,Fan,All movement yeah tax me.,"Braun, King and Rollins",Grooming Tools,992,USD,724,191126950284,Bisque,S,discontinued,49
2,3,Smart Speakerphone Charger Eco Plus Clean,Quickly inside pull line lay start.,Peck-Coleman,Fishing & Hunting,940,USD,769,7569143820621,Blue,Extra Large,pre_order,42
3,4,Premium Grill Trimmer Portable,Lawyer one than fire.,Hines Ltd,Skincare,324,USD,93,2705140928037,Ivory,50x70 cm,out_of_stock,93
4,5,Keyboard Freezer,Remain Congress blood plan voice.,"Spence, Webster and Orr",Laptops & Computers,908,USD,614,9830391008108,FloralWhite,10x10 cm,discontinued,91
5,6,Smart Fridge Plus,Tell tend provide government voice.,"Marks, Guzman and Cooley",Kitchen Appliances,627,USD,901,3039245054025,LightSalmon,XXL,pre_order,29
6,7,Compact Dock One Portable Wireless,Push role risk must get performance color.,Newman-Barajas,Fishing & Hunting,385,USD,366,6194768427002,MediumPurple,Large,out_of_stock,23
7,8,Premium Cooler Digital Portable X,Fall opportunity southern drive professor top.,"Gutierrez, Singleton and Downs",Skincare,296,USD,609,6978363826350,PaleGreen,8x10 in,in_stock,6
8,9,Compact Fan Scooter Headphones,Medical myself his piece agree.,Weber and Sons,Clothing & Apparel,870,USD,930,2666733210512,DarkBlue,XS,limited_stock,6
9,10,Eco Dock Air,Know hope enjoy budget have.,Humphrey and Sons,Beauty & Personal Care,602,USD,923,3726212774009,SandyBrown,50x70 cm,in_stock,11

In [28]:
#Standardising S to Small
def transform_data(df):
    df["Size"] = df["Size"].replace("S", "Small")
    return df

In [29]:
df = transform_data(df)
df

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Smart Fan Iron Cooker Go Wireless Portable,Catch enough role nearly.,Herman Ltd,Kids' Clothing,585,USD,194,3968600833473,Cornsilk,5x7 in,limited_stock,54
1,2,Fan,All movement yeah tax me.,"Braun, King and Rollins",Grooming Tools,992,USD,724,191126950284,Bisque,Small,discontinued,49
2,3,Smart Speakerphone Charger Eco Plus Clean,Quickly inside pull line lay start.,Peck-Coleman,Fishing & Hunting,940,USD,769,7569143820621,Blue,Extra Large,pre_order,42
3,4,Premium Grill Trimmer Portable,Lawyer one than fire.,Hines Ltd,Skincare,324,USD,93,2705140928037,Ivory,50x70 cm,out_of_stock,93
4,5,Keyboard Freezer,Remain Congress blood plan voice.,"Spence, Webster and Orr",Laptops & Computers,908,USD,614,9830391008108,FloralWhite,10x10 cm,discontinued,91
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,Powerbank,Yeah none boy fund city decision.,Castaneda-Harrison,Books & Stationery,567,USD,27,6519003997216,Cyan,Medium,pre_order,7
9996,9997,Rechargeable Lamp Scanner Vacuum,Appear country enter there pull thing computer.,Knapp-Key,Cycling,300,USD,177,4707959228979,MintCream,Large,limited_stock,55
9997,9998,Heater,Owner plan approach soldier church little little.,"Meyer, Case and Mills",Fitness Equipment,399,USD,996,5286509915488,LightGray,Large,pre_order,37
9998,9999,Rechargeable Headphones Stove,Base account partner probably.,Jones-Bell,Kitchen Appliances,45,USD,274,3702651384368,SlateBlue,12x18 in,in_stock,52
9999,10000,Clean Charger Treadmill,Return reflect truth tell scientist season.,Davis LLC,Sports & Outdoors,31,USD,46,8879838276060,Ivory,Medium,backorder,70

In [34]:
def load_data(df):
    df.to_csv("cleaned products-10000.csv", index=False)

In [42]:
df.to_csv( r"C:\Users\userlab\Desktop\peju_python_flow\cleaned_products.csv", index=False)