In [ ]:
#Question 1
# Question 1

# 1. Load dataset 1 into a pandas DataFrame
# 2. Perform necessary data cleaning and manipulation
# 3. Store the cleaned data in a new DataFrame
# 4. Export the cleaned DataFrame to a CSV file

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/userlab/Downloads/leads-1000.csv")

In [3]:
df

,Index,Account Id,Lead Owner,First Name,Last Name,Company,Phone 1,Phone 2,Email 1,Email 2,Website,Source,Deal Stage,Notes
0,1,862d63fBE445C3B,Antonio Savage,Cameron,Price,"Dean, Daniels and Charles",999-826-8118,+1-942-704-6437x07516,jermaine42@bush.info,howardtamara@malone-zamora.com,http://www.moody-colon.com/,Facebook Ads,Qualified,Be mind picture to.
1,2,B1B9fa4B9A41f10,Alexander Mccall,Phyllis,Wade,"Woodward, Everett and Doyle",821-857-6254,583.518.0548,dorothy36@shannon-dunn.info,qrangel@maxwell.org,https://nash.com/,Other,Closed Lost,Affect activity everybody cause sense close an...
2,3,1c2a1d1Ef8dDEFa,Nancy Grant,Matthew,Villegas,Mcfarland-Moore,001-449-523-9318x9353,652-505-2127,gregorybrenda@forbes.biz,fitzpatrickcole@jordan-massey.com,https://www.bradley-stanley.com/,Organic Search (SEO),Closed Lost,Strong cost together thought.
3,4,aEAFcec4C129DDE,Yesenia Short,Haley,Chapman,"Potts, Jimenez and Sweeney",472-744-2240x57147,241.390.0856x043,shelley22@villarreal.com,pvelazquez@thornton.com,https://day-hawkins.org/,Chatbot,Proposal Sent,Treatment opportunity drop.
4,5,6eA1Ab9d8d03966,Joan Meyers,Priscilla,Tran,Meza-Bolton,364.569.1151x738,+1-788-488-1036,kgutierrez@lyons.com,zlogan@andrade.com,http://nichols-hanson.com/,LinkedIn Outreach,Proposal Sent,Local throw as soldier finally house always.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2b3DF6736afc41B,Karla Solis,Andres,Mack,Chavez Group,651.647.1699,+1-682-797-7372,sethlewis@kane.org,deanshannon@rosario-vazquez.info,https://www.page.com/,Website Form,Closed Won,Total sister church wife action leader.
996,997,7DE8876cD9feb06,Jaime Alvarez,Kerry,Williamson,Ewing-Wilkinson,(359)458-9609,001-617-635-4771x21391,bartonmeghan@nolan.info,trivers@erickson.com,https://www.kane-willis.com/,LinkedIn Outreach,Closed Lost,Knowledge capital special operation consumer b...
997,998,49e703C20Ebd4d6,Ruth Cordova,Mark,Singh,"Mueller, Mcdonald and Moreno",341.287.1322x5936,(323)863-5915x212,nolanlindsay@carey.net,bowenanthony@liu-wallace.info,http://chung.com/,Networking Event,Proposal Sent,Indicate result past yet.
998,999,e8ABd3EBffA0DD2,Derek Lucero,Drew,Dodson,"Wiggins, Crawford and Lowe",+1-798-580-5257x2549,8525661123,edgar63@allen.com,patty00@dyer.com,http://smith-peters.com/,Other,Contacted,To seven throughout send article seven.
999,1000,E6a6c633B4AD579,Sonia Christian,Billy,Boyle,Morris Group,+1-819-664-6670,328.335.8434,zchase@bishop.com,vargasjudith@marquez.org,https://www.king-dougherty.biz/,Direct Traffic,New Lead,Especially property consumer ground event.

In [9]:
#renaming phone number
df.rename(columns={"Phone 1": "primary_number", "Phone 2": "secondary_number"}, inplace=True)

In [10]:
df["primary_number"]

0               999-826-8118
1               821-857-6254
2      001-449-523-9318x9353
3         472-744-2240x57147
4           364.569.1151x738
               ...
995             651.647.1699
996            (359)458-9609
997        341.287.1322x5936
998     +1-798-580-5257x2549
999          +1-819-664-6670
Name: primary_number, Length: 1000, dtype: object

In [11]:
df["secondary_number"]

0       +1-942-704-6437x07516
1                583.518.0548
2                652-505-2127
3            241.390.0856x043
4             +1-788-488-1036
                ...
995           +1-682-797-7372
996    001-617-635-4771x21391
997         (323)863-5915x212
998                8525661123
999              328.335.8434
Name: secondary_number, Length: 1000, dtype: object

In [12]:
#using the re package similar to regex in SQL to match validate and change strings
import re

In [18]:
#creating a function to standardising the phone number
def format_number_safe(phone_number):
    if pd.isna(phone_number):
        return None
    cleaned = re.sub(r"\D", "", str(phone_number))
    if len(cleaned) == 11 and cleaned.startswith("1"):
        cleaned = cleaned[1:]
    if len(cleaned) == 10:
        return f"+1 {cleaned[:3]} {cleaned[3:6]} {cleaned[6:]}"
    return None

In [19]:
df["primary_number"] = df["primary_number"].apply(format_number_safe)
df["secondary_number"] = df["secondary_number"].apply(format_number_safe)

In [20]:
df

,Index,Account Id,Lead Owner,First Name,Last Name,Company,primary_number,secondary_number,Email 1,Email 2,Website,Source,Deal Stage,Notes
0,1,862d63fBE445C3B,Antonio Savage,Cameron,Price,"Dean, Daniels and Charles",+1 999 826 8118,None,jermaine42@bush.info,howardtamara@malone-zamora.com,http://www.moody-colon.com/,Facebook Ads,Qualified,Be mind picture to.
1,2,B1B9fa4B9A41f10,Alexander Mccall,Phyllis,Wade,"Woodward, Everett and Doyle",+1 821 857 6254,+1 583 518 0548,dorothy36@shannon-dunn.info,qrangel@maxwell.org,https://nash.com/,Other,Closed Lost,Affect activity everybody cause sense close an...
2,3,1c2a1d1Ef8dDEFa,Nancy Grant,Matthew,Villegas,Mcfarland-Moore,None,+1 652 505 2127,gregorybrenda@forbes.biz,fitzpatrickcole@jordan-massey.com,https://www.bradley-stanley.com/,Organic Search (SEO),Closed Lost,Strong cost together thought.
3,4,aEAFcec4C129DDE,Yesenia Short,Haley,Chapman,"Potts, Jimenez and Sweeney",None,None,shelley22@villarreal.com,pvelazquez@thornton.com,https://day-hawkins.org/,Chatbot,Proposal Sent,Treatment opportunity drop.
4,5,6eA1Ab9d8d03966,Joan Meyers,Priscilla,Tran,Meza-Bolton,None,+1 788 488 1036,kgutierrez@lyons.com,zlogan@andrade.com,http://nichols-hanson.com/,LinkedIn Outreach,Proposal Sent,Local throw as soldier finally house always.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2b3DF6736afc41B,Karla Solis,Andres,Mack,Chavez Group,+1 651 647 1699,+1 682 797 7372,sethlewis@kane.org,deanshannon@rosario-vazquez.info,https://www.page.com/,Website Form,Closed Won,Total sister church wife action leader.
996,997,7DE8876cD9feb06,Jaime Alvarez,Kerry,Williamson,Ewing-Wilkinson,+1 359 458 9609,None,bartonmeghan@nolan.info,trivers@erickson.com,https://www.kane-willis.com/,LinkedIn Outreach,Closed Lost,Knowledge capital special operation consumer b...
997,998,49e703C20Ebd4d6,Ruth Cordova,Mark,Singh,"Mueller, Mcdonald and Moreno",None,None,nolanlindsay@carey.net,bowenanthony@liu-wallace.info,http://chung.com/,Networking Event,Proposal Sent,Indicate result past yet.
998,999,e8ABd3EBffA0DD2,Derek Lucero,Drew,Dodson,"Wiggins, Crawford and Lowe",None,+1 852 566 1123,edgar63@allen.com,patty00@dyer.com,http://smith-peters.com/,Other,Contacted,To seven throughout send article seven.
999,1000,E6a6c633B4AD579,Sonia Christian,Billy,Boyle,Morris Group,+1 819 664 6670,+1 328 335 8434,zchase@bishop.com,vargasjudith@marquez.org,https://www.king-dougherty.biz/,Direct Traffic,New Lead,Especially property consumer ground event.

In [23]:
df.sample(50)

,Index,Account Id,Lead Owner,First Name,Last Name,Company,primary_number,secondary_number,Email 1,Email 2,Website,Source,Deal Stage,Notes
539,540,BE2Febbf2eb92ef,Clayton Mcpherson,Audrey,Kelley,Odom Ltd,None,+1 834 744 9222,cesarjohns@allen.com,sloancaitlyn@goodwin.net,http://pennington.com/,Organic Search (SEO),Closed Won,Goal site hold maintain street.
67,68,D2FCE39fC51EabD,Edgar Vaughan,Dale,Warren,"Christensen, Skinner and Marquez",None,None,jonathonadkins@conner.com,harry44@oneill.com,http://www.dickerson.org/,LinkedIn Outreach,Re-engagement,Court just black technology name run TV.
412,413,3a5CBCB5fe73fF3,Tammie Nash,Holly,White,Salinas-Shelton,+1 378 999 1830,None,robin64@lopez.biz,ooneal@peck.com,http://www.little.com/,Organic Search (SEO),Negotiation,Yeah girl ever.
567,568,B7AdcF64dD7aCBA,Mia Herring,Tara,Taylor,Hurst-Coffey,None,None,nealgabriela@bautista-wilson.com,blakejessica@meadows-underwood.com,http://www.dougherty.com/,Content Marketing,Closed Won,Under power call eye voice nature individual.
988,989,b55f0d6cA25A9fb,Eduardo Norton,Shirley,Moses,Strong PLC,+1 931 752 4203,None,bestjoann@vance.com,carolynvalenzuela@estes.com,https://www.randall.net/,Cold Email,Closed Lost,Military realize knowledge.
614,615,77A7AA41CffC516,Shane Nielsen,Jill,Pena,Newton Ltd,None,None,dlindsey@frederick-gregory.com,juliajones@flowers.com,http://church.info/,Partner Program,Closed Lost,Modern live also themselves be.
770,771,c38017DEb27686B,April Edwards,Clinton,Atkins,Mann-Rice,+1 593 563 1860,None,smartin@arellano.com,copelandlonnie@benton.com,https://mccormick-glass.com/,Referral,Contacted,Purpose painting third suggest person characte...
572,573,45BCEf4f0bBE0E6,Nancy Keith,Harold,Hodge,Parker LLC,+1 673 497 0908,None,miguel61@lozano.com,laurenhurst@bolton-parsons.com,https://www.morgan.org/,Google Ads,Contacted,Room forget power green truth fine special.
534,535,2BDAB1EE5b234f8,Erik Moore,Leah,Carpenter,Gould-Newman,None,+1 687 679 7984,cspears@landry.net,gmorales@craig.com,https://ortega-yoder.com/,Networking Event,Negotiation,Argue hard close among.
186,187,6B9f7eeeD02c4E9,Jeanne Bridges,Donald,Wilcox,Pace PLC,+1 384 417 6857,None,carrie13@guerra.com,william13@haley-robbins.info,https://stein.com/,LinkedIn Outreach,New Lead,Case ok tough nation feel read.
727,728,A44e7EBffA8C1FF,Wanda Travis,Ricky,Elliott,"Cardenas, Kemp and Strong",None,None,martha99@morales-day.info,oheath@juarez.info,http://short-glover.org/,Purchased List,Proposal Sent,Assume staff lead.
786,787,25AC70cCBD7a6bb,Jennifer Payne,Bryan,Evans,"Chavez, Arnold and Henderson",+1 709 605 0917,+1 833 301 7887,madison57@hudson.com,kathryn81@palmer.info,https://pitts.com/,Cold Call,Negotiation,Drop break mind certain age walk.
380,381,3426Db0293f7063,Darrell Booth,Ebony,Jordan,Roach-Allison,+1 637 716 0411,+1 664 994 9320,guerraryan@stout.biz,vpierce@schmidt.com,https://mullins.net/,Cold Email,New Lead,Everyone near deep.
911,912,1ebAeAebEce4CbD,Dakota Franklin,Don,Ryan,Donovan Group,+1 833 334 6896,None,frenchedgar@douglas.com,bryan44@middleton.com,http://tucker.com/,Organic Search (SEO),On Hold,Event get open often activity radio do occur.
209,210,f0eFd7fDC1393FC,Chad Mccarthy,Diane,Schwartz,Winters LLC,None,None,ylove@lamb.net,annette90@horn-odom.com,https://www.watts.com/,Website Form,On Hold,Light from another player data where surface.
84,85,aAa7Ce72A9A37b2,Kristin Dunn,Brendan,Madden,"Casey, Garner and Hatfield",+1 726 649 3690,+1 367 296 7650,terrellkiara@guerra.net,harrellkaren@contreras.com,http://www.mcmillan.com/,Retargeting Ads,Proposal Sent,Arm north health.
981,982,cdCDd6FF4B8e9bE,Kari Robinson,Francis,Dean,"Luna, Acevedo and Chavez",None,None,jeremiahsanders@richards-baldwin.com,mistyprince@andrews.org,https://www.stout.com/,Cold Email,Qualified,Account call cup recent include ball camera.
22,23,Fe9C4eFD56EA7BE,Troy Newman,Mckenzie,Vargas,"Hebert, Graves and Duran",+1 296 694 3546,None,moyeralvin@livingston.info,paul92@gallagher.com,http://patrick.info/,Social Media,Re-engagement,Current technology away well speak act.
628,629,54A577b361e1E31,Sonya Avila,Brad,Stokes,Whitehead Ltd,None,None,gallaghergrace@stuart.net,dudleybreanna@ali.com,https://www.huerta.com/,Partner Program,Disqualified,Operation many radio it.
91,92,e2d5FAd408f4ea4,Eileen Dyer,Evan,Parks,"Bolton, Carr and Hart",None,None,lyonsluis@le-bailey.com,evanstevens@avery.info,http://chapman.com/,Chatbot,Negotiation,Response book edge window.
839,840,d3b331BaD2BA2c9,Wesley Delgado,Mark,Case,"Padilla, Walls and Small",+1 474 280 2369,+1 699 346 4404,rmatthews@hubbard.biz,stewartadrian@shepherd.biz,http://www.dawson.com/,Networking Event,Negotiation,Involve under without bit.
702,703,9e8a058fb378ded,Margaret Holland,Warren,Frey,Dunlap LLC,+1 577 769 0033,None,andres64@clements.com,bradfordchelsey@cooley.info,http://www.shields-hanna.biz/,Purchased List,Closed Won,Course sort cover sea security.
692,693,d47489461Db8C32,Beverly Acosta,Johnny,Randolph,Sweeney Ltd,None,None,qorr@ford-carrillo.net,robin65@murphy.com,https://acosta.com/,Networking Event,New Lead,After finish help state protect increase broth...
527,528,7a0d3e76Ae8cc8B,Marissa Taylor,Shelley,Leblanc,"Rogers, Mercado and Copeland",+1 491 630 6719,+1 522 485 7802,khogan@maynard.net,joecannon@clements.biz,http://dickson-ramsey.com/,Other,Disqualified,Agency month card.
224,225,f39CBb62d2ac295,Nancy Norris,Pamela,Bowman,"Landry, Wong and Fisher",None,None,rodneyduarte@wilkerson.com,traceyhunter@estes-merritt.com,http://vaughan.com/,Chatbot,New Lead,Region possible big marriage care.
571,572,f05464A1D1C9afA,Chad Duffy,Diane,Chan,Klein Ltd,None,+1 407 312 3423,patricia12@may-ibarra.com,evanellis@gonzalez.net,https://mccarthy.info/,Retargeting Ads,Proposal Sent,Interview anything crime find line.
24,25,87b3AEB2447dA62,Tracy Edwards,Chad,Mata,"Carney, Cantu and Sawyer",None,+1 626 432 9904,tylerjesse@hebert.info,vdowns@sims.com,https://www.guerra.info/,Partner Program,New Lead,Kind miss believe economic sense play.
231,232,aBbd2bE2A0F4f40,Glenda Mcneil,Krystal,Mccoy,"Robinson, Holmes and Jacobs",+1 949 647 9728,None,rodneywilson@lin-pratt.com,juanstephenson@baker-woodward.biz,http://www.wiley.com/,Purchased List,Disqualified,Now room general.
852,853,6D301e7cAF198f6,Franklin Richard,Haley,Hood,Vasquez-Vang,None,None,calebmurphy@arnold.biz,tammie65@house-mcintosh.net,http://www.oneal.com/,Purchased List,Negotiation,Stock effort run democratic yet later improve ...
251,252,22BD94c272fE9FE,Ebony Acosta,Janet,Glenn,Hernandez-Beasley,None,None,clopez@stone.org,alanvalenzuela@mcdonald-wilson.biz,https://durham.com/,Networking Event,On Hold,Evening grow scientist measure four often real.
749,750,6E2A5BeB72Da8Ea,Bill Mathews,Caleb,Sanchez,Ferguson Group,None,None,woodsjoy@rollins-boyle.com,curtisemma@rivas-barry.net,https://www.mcmahon.com/,Retargeting Ads,Contacted,Want us good contain worry drive sit.
826,827,BcFe181660Ed6b0,Jenna Madden,Wesley,Galvan,Fry-Carlson,+1 284 942 6862,None,kenneth65@arroyo-donaldson.info,fredtrevino@fitzgerald-nunez.com,http://www.stein.info/,Facebook Ads,Proposal Sent,Budget indicate team important black.
16,17,Ce2A5eb4dC72E18,Lindsay Ashley,Jerome,Hardy,Pena PLC,+1 618 471 8875,None,franklinfrye@melton.biz,jackiefuentes@lucero.net,http://www.hoffman-ray.com/,Networking Event,Qualified,Power ability important eye law democratic exp...
576,577,8DfDb8eec9DC3a9,Mandy Weber,Carrie,Hanna,Dawson-Sanchez,+1 981 985 5684,None,wileybradley@beard.com,billowens@gentry.com,https://mcintosh-elliott.com/,Webinars,Proposal Sent,Successful return professional fight.
919,920,57D5c9dA17d2cD2,Kathryn Mccall,Andrea,Roberts,"Atkinson, Mcfarland and Compton",None,+1 945 490 6918,englishchris@townsend.org,lindsay64@ortiz-molina.com,https://www.solomon.com/,Partner Program,Qualified,Write scene must involve.
225,226,1aeB109D9eeBBC9,Eddie Landry,Mitchell,Haley,Nicholson-Madden,None,None,sweeneybradley@butler.com,casey86@walker.com,http://meyers.com/,Facebook Ads,Contacted,Claim bank your there court now approach.
166,167,3D7E8BEfE642D50,Sonia Stewart,Christina,Yoder,Parks-Romero,None,+1 375 933 0361,pattersonbill@ball.com,westmarissa@morton.com,https://www.livingston.com/,Chatbot,Proposal Sent,Physical plant field sure three stay.
862,863,dDD5a7B4Fdca5fa,Melvin Decker,Allison,Ayers,"Scott, Schwartz and Peters",+1 309 979 3710,+1 214 231 9667,simstracy@curtis.net,maddoxcaroline@kane.org,https://boyle.info/,Organic Search (SEO),Contacted,Gas speech executive soon bag performance some...
453,454,880b4f705bAb2dA,Harry Powers,Erin,Casey,"Gilmore, Park and Woodward",None,+1 862 341 7309,kenneth30@schmidt-saunders.com,terryroberts@villegas.biz,https://reyes-simpson.com/,Partner Program,Proposal Sent,Ahead himself far others sign.
508,509,fAedDEA82205a3f,Felicia Estes,Rachael,Mcintyre,Meadows-Mendoza,None,+1 492 646 0927,kendra15@sherman-schultz.com,tylerbright@peterson-hopkins.com,http://www.tran.net/,Networking Event,Negotiation,She after culture four quality personal treatm...
757,758,9Aed4Aa79c31aec,Gabrielle Stone,Terri,Sullivan,Terry Ltd,None,None,xlucero@zamora.info,kbooker@ponce.com,https://hill-tucker.com/,Google Ads,Contacted,Culture full make middle safe.
965,966,FCda0c3516aF0bC,Charles Douglas,Sheena,Alvarado,"Banks, Hendricks and Glenn",+1 303 715 8817,None,glasshector@pineda.com,aleon@townsend.com,https://solis.com/,Other,New Lead,Nothing such article television home left around.
104,105,0412EaE3EcEaC64,Carrie Mathis,Julie,Ross,Romero PLC,None,+1 447 268 9789,hooperdarius@graves.biz,karibaldwin@hodges-ellison.com,https://www.singleton-miller.com/,Retargeting Ads,New Lead,Either sound do.
171,172,aB24bba3BBDcE1D,Julie Patton,Dave,Walsh,"Klein, Bailey and Bray",None,None,cassiebecker@powell.com,sandymcdowell@coffey.com,https://murillo.com/,Podcast,Re-engagement,Head save last method Mr major tax example.
402,403,8d33371F2c77cbd,Lynn Macias,Wesley,Koch,Powers Group,+1 490 371 4513,None,sotorobin@pacheco.info,alexandria51@becker-giles.org,https://www.solis.com/,Google Ads,Re-engagement,Indicate reduce recently fire campaign note so...
73,74,086044aEbfEF86F,Hector Fitzgerald,Nicole,Giles,"Bonilla, Myers and Perez",+1 573 560 4098,None,gordon08@barron.info,judithharding@church.com,https://www.castro-dougherty.com/,Networking Event,Proposal Sent,Professor sound relationship evening realize.
94,95,1cf9289cE937dA0,Jackson Short,Clifford,Herring,"Bond, Archer and Stephens",None,None,rmartinez@mcneil-bowman.com,qpace@lamb.net,http://cohen-hebert.com/,Networking Event,Contacted,Space live debate beautiful treatment signific...
441,442,8D9dF0A5EFbc7b7,Courtney Johnson,Tom,Berg,Page LLC,+1 471 740 3746,None,andrea97@brock.org,craiglandry@dennis.info,https://gonzales-arroyo.info/,Podcast,Closed Lost,Avoid industry teacher total build such.
585,586,9ae9FC3a87Abe03,Paula Ponce,Lee,Ford,Meyer-Lane,None,None,oscarmiller@bennett-vazquez.com,david66@bautista.net,http://joseph.com/,Organic Search (SEO),On Hold,Song suggest exactly much somebody character h...
633,634,9a6cDbb69BfEedd,George Pope,Cathy,Carson,Gilbert Group,None,None,shellybolton@pena.com,claytonrenee@price-snyder.net,http://www.herring-cole.com/,Referral,Closed Lost,Election story half voice his.

In [24]:
#store into a new data frame
df_cleaned = df.copy()  # or df_cleaned = df[["name", "primary_number", "secondary_number"]]

print(df_cleaned)

     Index       Account Id        Lead Owner First Name   Last Name  \
0        1  862d63fBE445C3B    Antonio Savage    Cameron       Price
1        2  B1B9fa4B9A41f10  Alexander Mccall    Phyllis        Wade
2        3  1c2a1d1Ef8dDEFa       Nancy Grant    Matthew    Villegas
3        4  aEAFcec4C129DDE     Yesenia Short      Haley     Chapman
4        5  6eA1Ab9d8d03966       Joan Meyers  Priscilla        Tran
..     ...              ...               ...        ...         ...
995    996  2b3DF6736afc41B       Karla Solis     Andres        Mack
996    997  7DE8876cD9feb06     Jaime Alvarez      Kerry  Williamson
997    998  49e703C20Ebd4d6      Ruth Cordova       Mark       Singh
998    999  e8ABd3EBffA0DD2      Derek Lucero       Drew      Dodson
999   1000  E6a6c633B4AD579   Sonia Christian      Billy       Boyle

                          Company   primary_number secondary_number  \
0       Dean, Daniels and Charles  +1 999 826 8118             None
1     Woodward, Everett and Doyle  +1 821 857 6254  +1 583 518 0548
2                 Mcfarland-Moore             None  +1 652 505 2127
3      Potts, Jimenez and Sweeney             None             None
4                     Meza-Bolton             None  +1 788 488 1036
..                            ...              ...              ...
995                  Chavez Group  +1 651 647 1699  +1 682 797 7372
996               Ewing-Wilkinson  +1 359 458 9609             None
997  Mueller, Mcdonald and Moreno             None             None
998    Wiggins, Crawford and Lowe             None  +1 852 566 1123
999                  Morris Group  +1 819 664 6670  +1 328 335 8434

                         Email 1                            Email 2  \
0           jermaine42@bush.info     howardtamara@malone-zamora.com
1    dorothy36@shannon-dunn.info                qrangel@maxwell.org
2       gregorybrenda@forbes.biz  fitzpatrickcole@jordan-massey.com
3       shelley22@villarreal.com            pvelazquez@thornton.com
4           kgutierrez@lyons.com                 zlogan@andrade.com
..                           ...                                ...
995           sethlewis@kane.org   deanshannon@rosario-vazquez.info
996      bartonmeghan@nolan.info               trivers@erickson.com
997       nolanlindsay@carey.net      bowenanthony@liu-wallace.info
998            edgar63@allen.com                   patty00@dyer.com
999            zchase@bishop.com           vargasjudith@marquez.org

                              Website                Source     Deal Stage  \
0         http://www.moody-colon.com/          Facebook Ads      Qualified
1                   https://nash.com/                 Other    Closed Lost
2    https://www.bradley-stanley.com/  Organic Search (SEO)    Closed Lost
3            https://day-hawkins.org/               Chatbot  Proposal Sent
4          http://nichols-hanson.com/     LinkedIn Outreach  Proposal Sent
..                                ...                   ...            ...
995             https://www.page.com/          Website Form     Closed Won
996      https://www.kane-willis.com/     LinkedIn Outreach    Closed Lost
997                 http://chung.com/      Networking Event  Proposal Sent
998          http://smith-peters.com/                 Other      Contacted
999   https://www.king-dougherty.biz/        Direct Traffic       New Lead

                                                 Notes
0                                  Be mind picture to.
1    Affect activity everybody cause sense close an...
2                        Strong cost together thought.
3                          Treatment opportunity drop.
4         Local throw as soldier finally house always.
..                                                 ...
995            Total sister church wife action leader.
996  Knowledge capital special operation consumer b...
997                          Indicate result past yet.
998            To seven throughout send article seven.
999         Especially property consumer ground event.

[1000 rows x 14 columns]

In [26]:
#export to csv
df_cleaned.to_csv("cleaned_phone_numbers.csv", index=False)

print("Standardised DataFrame!")

Standardised DataFrame!

In [30]:
df_cleaned.to_csv(r"C:\Users\userlab\Desktop\peju_python_flow\.csv", index=False)