In [134]:
import pandas as pd
from sqlalchemy import create_engine
#creating an engine function is for database interfacing and connectivity

In [135]:
import psycopg2
#is a database driver that allows python communicate with postgresql database

In [199]:
#pip show psycopg2

In [ ]:
#connecting sql alchemy to postgresql connection code to establish conn and write sql queries

In [137]:
engine = create_engine("postgresql+psycopg2://postgres:QztLWcoQoMcFPKoKgCyuDwUPjOHUYdtO@trolley.proxy.rlwy.net:50067/railway")

In [138]:
#running an sql query in python to result in a pd dataframe
df_categories = pd.read_sql(f" select * from public.categories", engine)

In [6]:
df_categories

,id,name,slug,is_active,created_at,updated_at
0,1,Electronics,electronics,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
1,2,Clothing,clothing,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
2,3,Books,books,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
3,4,Home & Kitchen,home-kitchen,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
4,5,Sports,sports,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00

In [139]:
df_coupons = pd.read_sql(f" select * from public.coupons", engine)

In [8]:
df_coupons

,id,code,discount_pct,max_uses,used_count,is_active,expires_at,created_at,updated_at
0,3,FLASH50,50.0,50,0,True,None,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
1,1,WELCOME10,10.0,500,1,True,None,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:58:50.366166+00:00
2,2,SAVE20,20.0,100,1,True,None,2026-03-11 02:31:45.075615+00:00,2026-03-11 13:30:44.214771+00:00

In [140]:
df_customers = pd.read_sql(f" select * from public.customers", engine)

In [10]:
df_customers

,id,first_name,last_name,email,phone,address,city,state,country,postal_code,password,is_active,created_at,updated_at
0,1,Test,User,testuser@test.com,None,None,None,None,Nigeria,None,$2b$12$8LYwj2E2rHoTauQlCWOKh.l.riliw5AWEDhZ6et...,True,2026-03-11 02:39:43.500028+00:00,2026-03-11 02:39:43.500028+00:00
1,2,Ahmed,Oladapo,biyiguy@gmail.com,+2349091390809,230 borno way,lagos,Abia,Nigeria,234101,$2b$12$fi1k5SMmbZWQ5hwIKi/cs.u4wjr8cKtiHNxAzzE...,True,2026-03-11 02:40:19.433485+00:00,2026-03-11 02:40:19.433485+00:00
2,53,Megan,Stephenson,donna55@example.com,001-292-983-4859,10808 Mary Mall Suite 271,Ibadan,None,Nigeria,None,$2b$12$tII5OYX1LCB7W/k7a6o3teAkMMGuGC59QHShF3....,True,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
3,54,Lauren,Flowers,judith52@example.net,(396)349-3118x207,9945 Pamela Field,Kano,None,Nigeria,None,$2b$12$UnXHrfcWhkPiTGn9yAzJ5eb19no19qluCIBRXb/...,True,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
4,55,Charles,Ramirez,proctorcharles@example.org,001-876-237-8316x690,951 Adam Mountains,Lagos,None,Nigeria,None,$2b$12$srDCNrvh0yiFZskuAoKVz.3kLptk5M5YQzTRnqL...,True,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,170,Amy,Bailey,lewisjustin@example.com,001-894-402-8752,167 Garrett Stravenue Suite 152,Ibadan,None,Nigeria,None,$2b$12$ajr9KWpgXw.FuZpN8C1doOcgcWDstJNPhNRLykf...,True,2026-03-11 02:56:30.034334+00:00,2026-03-11 02:56:30.034334+00:00
120,171,Kathryn,Lopez,nunezmargaret@example.org,341.522.6218,09137 Robert Pass,Enugu,None,Nigeria,None,$2b$12$8sWZO7BUWIuDVF2seIYkT..H0tRF.wa14aVzogy...,True,2026-03-11 02:56:30.034334+00:00,2026-03-11 02:56:30.034334+00:00
121,172,Cole,Miller,kelly73@example.net,576-639-6093,398 Decker Corner,Abuja,None,Nigeria,None,$2b$12$HKX3nfHTzPgWpjeeear1g.QQNM93qSQnFwvwiMt...,True,2026-03-11 02:56:30.034334+00:00,2026-03-11 02:56:30.034334+00:00
122,173,Chidinma,Okeh,chidinmaokeh75@gmail.com,+2348169101205,Alapere Lagos,Lagos,Lagos,Nigeria,None,$2b$12$DUeUjJ/LMQbRsRQgSR.EPOONYBe7jUeL/Q487cx...,True,2026-03-17 09:30:43.993873+00:00,2026-03-17 09:30:43.993873+00:00
123,174,Lola,Bakre,Lardivahapparels@gmail.com,9869986848769,23 seidu okeleji,Lagos,Logos,Nigeria,10001,$2b$12$4LX6meMWBLd2eI0extpfAOSKvkkAUw6YSVrSLu0...,True,2026-03-18 21:12:21.072851+00:00,2026-03-18 21:12:21.072851+00:00

In [142]:
df_inventory = pd.read_sql(f" select * from public.inventory", engine)

In [12]:
df_inventory.head(5)

,id,product_id,quantity,reorder_lvl,created_at,updated_at
0,2,2,499,20,2026-03-11 02:31:45.075615+00:00,2026-03-18 21:13:31.659486+00:00
1,4,4,499,20,2026-03-11 02:31:45.075615+00:00,2026-03-18 21:13:31.659486+00:00
2,6,6,499,20,2026-03-11 02:31:45.075615+00:00,2026-03-18 21:13:31.659486+00:00
3,14,14,496,20,2026-03-11 02:31:45.075615+00:00,2026-03-19 18:43:14.426457+00:00
4,3,3,499,20,2026-03-11 02:31:45.075615+00:00,2026-03-18 21:13:31.659486+00:00

In [143]:
df_order_items = pd.read_sql(f" select * from public.order_items", engine)

In [14]:
df_order_items.head(5)

,id,order_id,product_id,quantity,unit_price,total_price,created_at,updated_at
0,608,201,1,1,299.99,299.99,2026-03-11 02:47:25.274472+00:00,2026-03-11 02:47:25.274472+00:00
1,609,202,3,3,35.00,105.00,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
2,610,202,6,1,39.99,39.99,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
3,611,203,7,3,89.99,269.97,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
4,612,203,12,1,79.00,79.00,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00

In [144]:
df_orders = pd.read_sql(F" select * from public.orders", engine)

In [16]:
df_orders.head(5)

,id,customer_id,coupon_id,status,subtotal,discount_amount,total,notes,created_at,updated_at
0,201,1,NaN,pending,299.99,0.0,299.99,None,2026-03-11 02:47:25.274472+00:00,2026-03-11 02:47:25.274472+00:00
1,202,2,NaN,shipped,144.99,0.0,144.99,None,2025-11-15 02:31:46.083152+00:00,2025-11-15 02:31:46.083152+00:00
2,203,67,NaN,shipped,1023.92,0.0,1023.92,Buy history pass professional technology not.,2025-11-06 00:17:46.235412+00:00,2025-11-06 00:17:46.235412+00:00
3,204,54,NaN,delivered,923.97,0.0,923.97,None,2025-09-12 06:40:46.603995+00:00,2025-09-12 06:40:46.603995+00:00
4,205,2,NaN,delivered,594.93,0.0,594.93,None,2026-01-03 11:41:47.019277+00:00,2026-01-03 11:41:47.019277+00:00

In [145]:
df_payments = pd.read_sql(f" select * from public.payments", engine)

In [18]:
df_payments.head(5)

,id,order_id,method,status,amount,reference,created_at,updated_at
0,201,201,card,completed,299.99,bfc477cb-7093-4442-819b-1e54bfe69c12,2026-03-11 02:47:25.274472+00:00,2026-03-11 02:47:25.274472+00:00
1,202,202,paypal,completed,144.99,b53fd75f-1ef3-4a95-8f45-5accea26255c,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
2,203,203,bank_transfer,completed,1023.92,71e4ae4c-6fbd-400f-8522-3118eef261dc,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
3,204,204,paypal,completed,923.97,ae1cff6e-ff98-49d5-8321-c78cd6bd50d7,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
4,205,205,card,completed,594.93,5d85bf0f-2ecd-40f9-8039-af3358599156,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00

In [146]:
df_products = pd.read_sql(f" select * from public.products", engine)

In [20]:
df_products.head(5)

,id,category_id,name,slug,description,price,image_url,is_active,created_at,updated_at
0,1,1,Samsung Galaxy A54,samsung-galaxy-a54,Mid-range Android smartphone,299.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
1,2,1,Wireless Earbuds Pro,wireless-earbuds-pro,Noise-cancelling wireless earbuds,49.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
2,3,1,USB-C Hub 7-in-1,usb-c-hub-7in1,Multiport USB-C adapter,35.00,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
3,4,1,Mechanical Keyboard,mechanical-keyboard,"TKL mechanical keyboard, red switches",79.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
4,5,2,Classic White Tee,classic-white-tee,100% cotton unisex t-shirt,15.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00

In [147]:
df_reviews = pd.read_sql(f" select * from public.reviews", engine)

In [22]:
df_reviews.head(5)

,id,product_id,customer_id,rating,comment,created_at,updated_at
0,21,1,58,1,Him performance clearly part answer kitchen th...,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
1,22,1,62,5,Interesting television early recent generation.,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
2,23,12,66,5,Remain check set name culture consumer him lik...,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
3,24,4,1,3,Ball same movie structure human save share.,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
4,25,2,2,1,None,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00

In [148]:
df_shipping = pd.read_sql(f" select * from public.shipping", engine)

In [24]:
df_shipping.tail(5)

,id,order_id,status,carrier,tracking_number,address,city,state,country,postal_code,shipped_at,delivered_at,created_at,updated_at
558,758,759,not_shipped,None,None,230 borno way,lagos,Abia,Nigeria,234101,NaT,NaT,2026-03-11 13:30:44.214771+00:00,2026-03-11 13:30:44.214771+00:00
559,759,760,not_shipped,None,None,230 borno way,lagos,Abia,Nigeria,234101,NaT,NaT,2026-03-15 11:57:26.642021+00:00,2026-03-15 11:57:26.642021+00:00
560,760,761,not_shipped,None,None,23 seidu okeleji,Lagos,Logos,Nigeria,10001,NaT,NaT,2026-03-18 21:13:31.659486+00:00,2026-03-18 21:13:31.659486+00:00
561,761,762,not_shipped,None,None,230 borno way,lagos,Abia,Nigeria,234101,NaT,NaT,2026-03-19 07:40:46.529276+00:00,2026-03-19 07:40:46.529276+00:00
562,762,763,not_shipped,None,None,230 borno way,lagos,Abia,Nigeria,234101,NaT,NaT,2026-03-19 18:43:14.426457+00:00,2026-03-19 18:43:14.426457+00:00

In [149]:
from sqlalchemy import inspect
#this function creates an introspection object that gets info about daabase and retrieve columns

In [150]:
insp = inspect(engine)
#examines schemas, table and columns, keys etc

In [151]:
#engine = create_engine("postgresql+psycopg2://postgres:QztLWcoQoMcFPKoKgCyuDwUPjOHUYdtO@trolley.proxy.rlwy.net:50067/railway")

In [152]:
table_names = insp.get_table_names(schema='public')
print("table_names:\n", table_names)
#insp get the table from schema and returns a table list as strings, for verification

table_names:
 ['categories', 'products', 'customers', 'orders', 'coupons', 'order_items', 'payments', 'shipping', 'inventory', 'reviews']

In [29]:
#table_list = ["categories", "coupons", "customers", "inventory", "order_items", "orders", "payments", "products", "reviews", "shipping"]

In [ ]:
#mapping tables to sql queries in a .py it allows iteration

In [153]:
table_dict = {"categories": "select * from categories", 
          "coupons": "select * from coupons", 
          "customers": "select * from customers",
          "inventory": "select * from inventory",
         "order_items": "select * from order_items",
         "orders": "select * from orders",
         "payments": "select * from payments",
         "products": "select * from products",
         "reviews": "select * from reviews",
         "shipping": "select * from shipping"}

In [109]:
table_dict

{'categories': 'select * from categories',
 'coupons': 'select * from coupons',
 'customers': 'select * from customers',
 'inventory': 'select * from inventory',
 'order_items': 'select * from order_items',
 'orders': 'select * from orders',
 'payments': 'select * from payments',
 'products': 'select * from products',
 'reviews': 'select * from reviews',
 'shipping': 'select * from shipping'}

In [32]:
#dfs_list = []

In [34]:
#for table in table_list:
    #dfs_[table] = pd.read_sql(f" select * from {table}", engine)
    #dfs_list.append(dfs)

In [ ]:
#dfs_list[0

In [154]:
dfs_dict = {}

In [155]:
for table_name, sql_query in table_dict.items():
    df = pd.read_sql(sql_query, engine)
    dfs_dict[table_name] = df

In [156]:
categories_df = dfs_dict["categories"]

In [44]:
categories_df.tail(10)

,id,name,slug,is_active,created_at,updated_at
0,1,Electronics,electronics,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
1,2,Clothing,clothing,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
2,3,Books,books,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
3,4,Home & Kitchen,home-kitchen,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
4,5,Sports,sports,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00

In [157]:
coupons_df = dfs_dict["coupons"]

In [46]:
coupons_df.tail(5)

,id,code,discount_pct,max_uses,used_count,is_active,expires_at,created_at,updated_at
0,3,FLASH50,50.0,50,0,True,None,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
1,1,WELCOME10,10.0,500,1,True,None,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:58:50.366166+00:00
2,2,SAVE20,20.0,100,1,True,None,2026-03-11 02:31:45.075615+00:00,2026-03-11 13:30:44.214771+00:00

In [158]:
customer_df = dfs_dict["customers"]

In [48]:
customer_df.head(8)

,id,first_name,last_name,email,phone,address,city,state,country,postal_code,password,is_active,created_at,updated_at
0,1,Test,User,testuser@test.com,None,None,None,None,Nigeria,None,$2b$12$8LYwj2E2rHoTauQlCWOKh.l.riliw5AWEDhZ6et...,True,2026-03-11 02:39:43.500028+00:00,2026-03-11 02:39:43.500028+00:00
1,2,Ahmed,Oladapo,biyiguy@gmail.com,+2349091390809,230 borno way,lagos,Abia,Nigeria,234101,$2b$12$fi1k5SMmbZWQ5hwIKi/cs.u4wjr8cKtiHNxAzzE...,True,2026-03-11 02:40:19.433485+00:00,2026-03-11 02:40:19.433485+00:00
2,53,Megan,Stephenson,donna55@example.com,001-292-983-4859,10808 Mary Mall Suite 271,Ibadan,None,Nigeria,None,$2b$12$tII5OYX1LCB7W/k7a6o3teAkMMGuGC59QHShF3....,True,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
3,54,Lauren,Flowers,judith52@example.net,(396)349-3118x207,9945 Pamela Field,Kano,None,Nigeria,None,$2b$12$UnXHrfcWhkPiTGn9yAzJ5eb19no19qluCIBRXb/...,True,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
4,55,Charles,Ramirez,proctorcharles@example.org,001-876-237-8316x690,951 Adam Mountains,Lagos,None,Nigeria,None,$2b$12$srDCNrvh0yiFZskuAoKVz.3kLptk5M5YQzTRnqL...,True,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
5,56,Anna,James,colin49@example.org,630.904.8380x57060,8721 Garcia Meadow,Kano,None,Nigeria,None,$2b$12$GCVNV1JBbZwOfjQF1r0yneVdL.y0IwZZ1nQCajX...,True,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
6,57,Kristen,Williams,cynthiagibbs@example.net,001-846-309-3999x390,2098 Monica Street,Port Harcourt,None,Nigeria,None,$2b$12$mHGPZAFx8xGKXieDSu32kenQEritCmDchMxvfiE...,True,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
7,58,Michael,Davidson,woodryan@example.com,+1-659-361-2318x7091,6549 Thomas Route,Lagos,None,Nigeria,None,$2b$12$Tagc8s3czreLqChAeX5QAe0.s/jjFMT5Akv5B/r...,True,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00

In [159]:
inventory_df = dfs_dict["inventory"]

In [50]:
inventory_df.head(5)

,id,product_id,quantity,reorder_lvl,created_at,updated_at
0,2,2,499,20,2026-03-11 02:31:45.075615+00:00,2026-03-18 21:13:31.659486+00:00
1,4,4,499,20,2026-03-11 02:31:45.075615+00:00,2026-03-18 21:13:31.659486+00:00
2,6,6,499,20,2026-03-11 02:31:45.075615+00:00,2026-03-18 21:13:31.659486+00:00
3,14,14,496,20,2026-03-11 02:31:45.075615+00:00,2026-03-19 18:43:14.426457+00:00
4,3,3,499,20,2026-03-11 02:31:45.075615+00:00,2026-03-18 21:13:31.659486+00:00

In [160]:
order_items_df = dfs_dict["order_items"]

In [52]:
order_items_df.head(5)

,id,order_id,product_id,quantity,unit_price,total_price,created_at,updated_at
0,608,201,1,1,299.99,299.99,2026-03-11 02:47:25.274472+00:00,2026-03-11 02:47:25.274472+00:00
1,609,202,3,3,35.00,105.00,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
2,610,202,6,1,39.99,39.99,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
3,611,203,7,3,89.99,269.97,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
4,612,203,12,1,79.00,79.00,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00

In [161]:
orders_df = dfs_dict["orders"]

In [54]:
orders_df.head(5)

,id,customer_id,coupon_id,status,subtotal,discount_amount,total,notes,created_at,updated_at
0,201,1,NaN,pending,299.99,0.0,299.99,None,2026-03-11 02:47:25.274472+00:00,2026-03-11 02:47:25.274472+00:00
1,202,2,NaN,shipped,144.99,0.0,144.99,None,2025-11-15 02:31:46.083152+00:00,2025-11-15 02:31:46.083152+00:00
2,203,67,NaN,shipped,1023.92,0.0,1023.92,Buy history pass professional technology not.,2025-11-06 00:17:46.235412+00:00,2025-11-06 00:17:46.235412+00:00
3,204,54,NaN,delivered,923.97,0.0,923.97,None,2025-09-12 06:40:46.603995+00:00,2025-09-12 06:40:46.603995+00:00
4,205,2,NaN,delivered,594.93,0.0,594.93,None,2026-01-03 11:41:47.019277+00:00,2026-01-03 11:41:47.019277+00:00

In [162]:
payments_df = dfs_dict["payments"]

In [56]:
payments_df.head(5)

,id,order_id,method,status,amount,reference,created_at,updated_at
0,201,201,card,completed,299.99,bfc477cb-7093-4442-819b-1e54bfe69c12,2026-03-11 02:47:25.274472+00:00,2026-03-11 02:47:25.274472+00:00
1,202,202,paypal,completed,144.99,b53fd75f-1ef3-4a95-8f45-5accea26255c,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
2,203,203,bank_transfer,completed,1023.92,71e4ae4c-6fbd-400f-8522-3118eef261dc,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
3,204,204,paypal,completed,923.97,ae1cff6e-ff98-49d5-8321-c78cd6bd50d7,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
4,205,205,card,completed,594.93,5d85bf0f-2ecd-40f9-8039-af3358599156,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00

In [163]:
products_df = dfs_dict["products"]

In [58]:
products_df.head(5)

,id,category_id,name,slug,description,price,image_url,is_active,created_at,updated_at
0,1,1,Samsung Galaxy A54,samsung-galaxy-a54,Mid-range Android smartphone,299.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
1,2,1,Wireless Earbuds Pro,wireless-earbuds-pro,Noise-cancelling wireless earbuds,49.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
2,3,1,USB-C Hub 7-in-1,usb-c-hub-7in1,Multiport USB-C adapter,35.00,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
3,4,1,Mechanical Keyboard,mechanical-keyboard,"TKL mechanical keyboard, red switches",79.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
4,5,2,Classic White Tee,classic-white-tee,100% cotton unisex t-shirt,15.99,None,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00

In [164]:
reviews_df = dfs_dict["reviews"]

In [60]:
reviews_df.head(5)

,id,product_id,customer_id,rating,comment,created_at,updated_at
0,21,1,58,1,Him performance clearly part answer kitchen th...,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
1,22,1,62,5,Interesting television early recent generation.,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
2,23,12,66,5,Remain check set name culture consumer him lik...,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
3,24,4,1,3,Ball same movie structure human save share.,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
4,25,2,2,1,None,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00

In [165]:
shipping_df = dfs_dict["shipping"]

In [62]:
shipping_df.head(5)

,id,order_id,status,carrier,tracking_number,address,city,state,country,postal_code,shipped_at,delivered_at,created_at,updated_at
0,200,201,not_shipped,None,None,123 Test St,Lagos,None,Nigeria,None,NaT,NaT,2026-03-11 02:47:25.274472+00:00,2026-03-11 02:47:25.274472+00:00
1,201,202,in_transit,FedEx,BF61506170282,230 borno way,lagos,None,Nigeria,None,2025-11-16 02:31:46.083152+00:00,NaT,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
2,202,203,in_transit,FedEx,QG37272864561,1042 Joseph Motorway,Lagos,None,Nigeria,None,2025-11-07 00:17:46.235412+00:00,NaT,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
3,203,204,delivered,DHL,JL37932870874,9945 Pamela Field,Kano,None,Nigeria,None,2025-09-13 06:40:46.603995+00:00,2025-09-22 06:40:46.603995+00:00,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00
4,204,205,delivered,DHL,KC27343694512,230 borno way,lagos,None,Nigeria,None,2026-01-04 11:41:47.019277+00:00,2026-01-10 11:41:47.019277+00:00,2026-03-11 02:48:42.266872+00:00,2026-03-11 02:48:42.266872+00:00

In [166]:
from sqlalchemy import create_engine, inspect

In [167]:
insp = inspect(engine)

In [168]:
engine = create_engine("postgresql+psycopg2://postgres:QztLWcoQoMcFPKoKgCyuDwUPjOHUYdtO@trolley.proxy.rlwy.net:50067/railway")

In [169]:
table_names = insp.get_table_names(schema='public')
print("table_names:\n", table_names)

table_names:
 ['categories', 'products', 'customers', 'orders', 'coupons', 'order_items', 'payments', 'shipping', 'inventory', 'reviews']

#Installing packages to send data to snowflake warehouse

In [200]:
#pip install snowflake-connector-python pandas

In [170]:
import snowflake.connector
from snowflake.connector.pandas_tools import write_pandas
#imports the helper function that uploads a pandas DataFrame into a Snowflake table

In [184]:
# Snowflake connection parameters
conn = snowflake.connector.connect(
    user='SPEJU',
    password='#Snowflakes2025',
    account='NZPMXUO-DA03027',  # e.g., 'abcd1234.us-east-1'
    warehouse='COMPUTE_WH',
    database='PEJU_DATABASE2',
    schema='PEJU_SCHEMA2')

In [185]:
# Create a cursor object to connect to sql 
cursor = conn.cursor()

In [ ]:
#df.columns = [col.upper() for col in df.columns]

In [187]:
peju_database2 = "PEJU_DATABASE2"  # Replace with your actual database name

success, nchunks, nrows, _ = write_pandas(
    conn,
    categories_df,
    "categories",
    auto_create_table = True,
    database = peju_database,
    schema = "PEJU_SCHEMA2"
)

C:\Users\userlab\AppData\Local\Temp\ipykernel_24620\1574297020.py:3: UserWarning: Dataframe contains a datetime with timezone column, but 'use_logical_type=None'. This can result in datetimes being incorrectly written to Snowflake. Consider setting 'use_logical_type = True'
  success, nchunks, nrows, _ = write_pandas(

In [198]:
peju_database2 = "PEJU_DATABASE2"  # Replace with your actual database name

success, nchunks, nrows, _ = write_pandas(
    conn,
    coupons_df,
    "coupons",
    auto_create_table = True,
    database = peju_database2,
    schema = "PEJU_SCHEMA2",
)

C:\Users\userlab\AppData\Local\Temp\ipykernel_24620\2745357514.py:3: UserWarning: Dataframe contains a datetime with timezone column, but 'use_logical_type=None'. This can result in datetimes being incorrectly written to Snowflake. Consider setting 'use_logical_type = True'
  success, nchunks, nrows, _ = write_pandas(

In [190]:
# Define the peju_database variable before using it
peju_database = "PEJU_DATABASE2"  # Replace with your actual database name

success, nchunks, nrows, _ = write_pandas(
    conn,
    customer_df,
    "customers",
    auto_create_table = True,
    database = peju_database,
    schema = "PEJU_SCHEMA2"
)

C:\Users\userlab\AppData\Local\Temp\ipykernel_24620\3773846722.py:4: UserWarning: Dataframe contains a datetime with timezone column, but 'use_logical_type=None'. This can result in datetimes being incorrectly written to Snowflake. Consider setting 'use_logical_type = True'
  success, nchunks, nrows, _ = write_pandas(

In [191]:
peju_database = "PEJU_DATABASE2"  # Replace with your actual database name

success, nchunks, nrows, _ = write_pandas(
    conn,
    inventory_df,
    "inventory",
    auto_create_table = True,
    database = peju_database,
    schema = "PEJU_SCHEMA2")

C:\Users\userlab\AppData\Local\Temp\ipykernel_24620\282655098.py:3: UserWarning: Dataframe contains a datetime with timezone column, but 'use_logical_type=None'. This can result in datetimes being incorrectly written to Snowflake. Consider setting 'use_logical_type = True'
  success, nchunks, nrows, _ = write_pandas(

In [192]:
peju_database = "PEJU_DATABASE2"  # Replace with your actual database name

success, nchunks, nrows, _ = write_pandas(
    conn,
    orders_df,
    "orders",
    auto_create_table = True,
    database = peju_database,
    schema = "PEJU_SCHEMA2")

C:\Users\userlab\AppData\Local\Temp\ipykernel_24620\638441669.py:3: UserWarning: Dataframe contains a datetime with timezone column, but 'use_logical_type=None'. This can result in datetimes being incorrectly written to Snowflake. Consider setting 'use_logical_type = True'
  success, nchunks, nrows, _ = write_pandas(

In [193]:
peju_database = "PEJU_DATABASE2"  # Replace with your actual database name

success, nchunks, nrows, _ = write_pandas(
    conn,
    order_items_df,
    "order_items",
    auto_create_table = True,
    database = peju_database,
    schema = "PEJU_SCHEMA2")

C:\Users\userlab\AppData\Local\Temp\ipykernel_24620\830894202.py:3: UserWarning: Dataframe contains a datetime with timezone column, but 'use_logical_type=None'. This can result in datetimes being incorrectly written to Snowflake. Consider setting 'use_logical_type = True'
  success, nchunks, nrows, _ = write_pandas(

In [194]:
peju_database = "PEJU_DATABASE2"  # Replace with your actual database name

success, nchunks, nrows, _ = write_pandas(
    conn,
    payments_df,
    "payments",
    auto_create_table = True,
    database = peju_database,
    schema = "PEJU_SCHEMA2")

C:\Users\userlab\AppData\Local\Temp\ipykernel_24620\3398424392.py:3: UserWarning: Dataframe contains a datetime with timezone column, but 'use_logical_type=None'. This can result in datetimes being incorrectly written to Snowflake. Consider setting 'use_logical_type = True'
  success, nchunks, nrows, _ = write_pandas(

In [197]:
peju_database = "PEJU_DATABASE2"  # Replace with your actual database name

success, nchunks, nrows, _ = write_pandas(
    conn,
    reviews_df,
    "reviews",
    auto_create_table = True,
    database = peju_database,
    schema = "PEJU_SCHEMA2")

C:\Users\userlab\AppData\Local\Temp\ipykernel_24620\1382582101.py:3: UserWarning: Dataframe contains a datetime with timezone column, but 'use_logical_type=None'. This can result in datetimes being incorrectly written to Snowflake. Consider setting 'use_logical_type = True'
  success, nchunks, nrows, _ = write_pandas(

In [195]:
peju_database = "PEJU_DATABASE2"  # Replace with your actual database name

success, nchunks, nrows, _ = write_pandas(
    conn,
    products_df,
    "products",
    auto_create_table = True,
    database = peju_database,
    schema = "PEJU_SCHEMA2")

C:\Users\userlab\AppData\Local\Temp\ipykernel_24620\3588386757.py:3: UserWarning: Dataframe contains a datetime with timezone column, but 'use_logical_type=None'. This can result in datetimes being incorrectly written to Snowflake. Consider setting 'use_logical_type = True'
  success, nchunks, nrows, _ = write_pandas(

In [196]:
peju_database = "PEJU_DATABASE2"  # Replace with your actual database name

success, nchunks, nrows, _ = write_pandas(
    conn,
    shipping_df,
    "shipping",
    auto_create_table = True,
    database = peju_database,
    schema = "PEJU_SCHEMA2",
)

C:\Users\userlab\AppData\Local\Temp\ipykernel_24620\949790587.py:3: UserWarning: Dataframe contains a datetime with timezone column, but 'use_logical_type=None'. This can result in datetimes being incorrectly written to Snowflake. Consider setting 'use_logical_type = True'
  success, nchunks, nrows, _ = write_pandas(