In [9]:
#Given two lists of students who attended different classes
class_a = ["John", "Mary", "Peter", "John", "Sarah"]
class_b = ["Peter", "Daniel", "Mary", "Mary", "Paul"]

#Tasks:
#Convert both to sets
#Remove duplicates automatically
#Find students that attended both classes
#Find students that attended only classes A

#1 convert both to sets #2 Print all results and Remove duplicates automatically
set_a = set(class_a)
set_b = set(class_b)
students = set_a | set_b
print(students)

#3 Find students that attended both classes
print(set_a.intersection(set_b))

#4 Find students that attended only classes a
print(set_a.difference(set_b))

{'Daniel', 'Paul', 'John', 'Mary', 'Peter', 'Sarah'}
{'Mary', 'Peter'}
{'John', 'Sarah'}

In [29]:
#create a list of 5 students name
#Add one more student
#Remove one student
#print final list
#create a list of 5 students name
students = ["Peju", "Temi", "Tope", "Anike", "Sokunle"]
#Add one more student
students.append("Chizaram")
print(students)
#Remove one student
students.pop(-2)
#print final list
print(students)

['Peju', 'Temi', 'Tope', 'Anike', 'Sokunle', 'Chizaram']
['Peju', 'Temi', 'Tope', 'Anike', 'Chizaram']

In [63]:
#Print numbers from 1 to 20 using a for loop.
for numbers in range (1, 21):
    print(numbers)

#Print only even numbers from 1 to 20.
for numbers in range(1, 21):
    if numbers % 2 == 0:
        print(numbers)

#Print the square of each number from 1 to 10.
for numbers in range(1, 11):
        print(numbers ** 2)

#Given a list [4, 7, 1, 9, 3], print each element.
numbers = [4, 7, 1, 9, 3]
for number in numbers:
    print(number)
#Count how many numbers in a list are greater than 5.
numbers = [4, 7, 1, 9, 3]
count = 0
for number in numbers:
    if number > 5:
        count += 1
print(count)
#Find the sum of all elements in a list without using sum().
numbers = [1, 2, 3, 4, 5]
Total = 0
for number in numbers:
    Total += number 
print("Sum:", Total)
#Find the maximum value in a list without using max().
numbers = [1, 2, 3, 4, 5]
largest = numbers[0]
for number in numbers:
    if number > largest:
        largest = number
print("Maximum:", largest)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
2
4
6
8
10
12
14
16
18
20
1
4
9
16
25
36
49
64
81
100
4
7
1
9
3
2
Sum: 15
Maximum: 5

In [82]:
#Write a Python function that accepts two integer numbers. 
#If the product of the two numbers is less than or equal to 1000, return their product; otherwise, return their sum.
def calculate_result(num1, num2):
    product = num1 * num2
    
    if product <= 1000:
        return product
    else:
        return num1 + num2

In [84]:
#Iterate through the first 10 numbers (0–9). In each iteration, print the current number, the previous number, and their sum.

previous_num = 0

for current_num in range(0, 10):
    total = current_num + previous_num
    print("Current:", current_num,
          "Previous:", previous_num,
          "Sum:", total)
    
    previous_num = current_num

Current: 0 Previous: 0 Sum: 0
Current: 1 Previous: 0 Sum: 1
Current: 2 Previous: 1 Sum: 3
Current: 3 Previous: 2 Sum: 5
Current: 4 Previous: 3 Sum: 7
Current: 5 Previous: 4 Sum: 9
Current: 6 Previous: 5 Sum: 11
Current: 7 Previous: 6 Sum: 13
Current: 8 Previous: 7 Sum: 15
Current: 9 Previous: 8 Sum: 17

In [91]:
#Create a list of 5 fruits. Add a new fruit to the end of the list, then remove the second fruit (at index 1).
fruits = ["apple", "pineapple", "mango", "banana", "coconut"]
fruits.append("pawpaw")
print(fruits)
#Remove
fruits.pop(1)
print(fruits)

['apple', 'pineapple', 'mango', 'banana', 'coconut', 'pawpaw']
['apple', 'mango', 'banana', 'coconut', 'pawpaw']

In [98]:
#Write a program that takes a string and reverses it (e.g., “Python” becomes “nohtyP”).

# Write a program that takes a string and reverses it (e.g., "Python" becomes "nohtyP").
text = "python"
reversed_text = text[::-1]  # Added 'text' before the slice notation
print(f"Original: {text}")
print(f"Reversed: {reversed_text}")

Original: python
Reversed: nohtyp

In [99]:
 #Write a program to count the total number of vowels (a, e, i, o, u) present in a given sentence "python is amazing"
sentence = "python is amazing"
vowels = "aeiou"
count = 0
for char in sentence.lower(): #Go through the sentence one character at a time.”
    if char in vowels:        #Check if the current character is inside the string "aeiou".”
        count += 1 #If the condition is true, increase the vowel count
print("Total vowels:", count)

Total vowels: 5

In [106]:
 #Given a list of integers, find and print both the largest and the smallest numbers.
nums = [45, 2, 89, 12, 7]
largest = max(nums)
smallest = min(nums)    
print("largest:", largest)
print("smallest:", smallest)

largest: 89
smallest: 2

In [112]:
 #Write a function to return True if the first and last number of a given list is the same. If the numbers are different, return False
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]
def check_first_last(numbers):
    if numbers[0] == numbers[-1]:
        return True
    else:
        return False
print(check_first_last(numbers_x))
print(check_first_last(numbers_y))

True
False

In [1]:
#importing pandas
import pandas as pd

In [6]:
#loading data frames
# Method 1: Use raw string by adding 'r' prefix
df = pd.read_csv(r"C:\Users\userlab\Downloads\orders.csv")

# Method 2: Use forward slashes instead of backslashes
# df = pd.read_csv("C:/Users/userlab/Downloads/orders.csv")

# Method 3: Use double backslashes to escape them
# df = pd.read_csv("C:\\Users\\userlab\\Downloads\\orders.csv")

In [7]:
print(df)

    OrderID      CustomerName                Product     Category  Quantity  \
0      1001        John Smith                 Laptop  Electronics         1
1      1002         Sarah Lee             Headphones  Electronics         2
2      1003          Ali Khan           Office Chair    Furniture         1
3      1004        Alice Wong              Desk Lamp    Furniture         3
4      1005     Carlos Mendez               Keyboard  Electronics         2
5      1006      Nora Ibrahim               Notebook   Stationery         5
6      1007       Emily Davis          Standing Desk    Furniture         1
7      1008        James Park                Monitor  Electronics         2
8      1009       Maria Rossi                    Pen   Stationery        10
9      1010  Takeshi Nakamura                  Mouse  Electronics         1
10     1011     Sophie Martin                 Webcam  Electronics         1
11     1012         Raj Patel           File Cabinet    Furniture         2
12     1013       Emma Wilson                Stapler   Stationery         3
13     1014   Diego Rodriguez              USB Drive  Electronics         5
14     1015         Lisa Chen              Bookshelf    Furniture         1
15     1016      Ahmed Hassan          Printer Paper   Stationery        20
16     1017     Anna Kowalski         Wireless Mouse  Electronics         2
17     1018     Michael Brown         Desk Organizer    Furniture         1
18     1019       Yuki Tanaka             Calculator  Electronics         1
19     1020   Fatima Al-Zahra             Whiteboard    Furniture         1
20     1021    David Thompson           Highlighters   Stationery         8
21     1022    Isabella Silva      Bluetooth Speaker  Electronics         1
22     1023    Oliver Schmidt           Office Plant    Furniture         2
23     1024        Zara Ahmed           Sticky Notes   Stationery        15
24     1025    Lucas Anderson           Tablet Stand  Electronics         1
25     1026      Chloe Dubois         Paper Shredder  Electronics         1
26     1027     Miguel Torres         Desk Chair Mat    Furniture         1
27     1028       Nina Petrov           Binder Clips   Stationery        12
28     1029      Seo-yeon Kim      Wireless Keyboard  Electronics         1
29     1030   Giuseppe Romano          Desk Calendar    Furniture         1
30     1031      Amira Hassan                USB Hub  Electronics         1
31     1032     Thomas Müller       Document Scanner  Electronics         1
32     1033   Sofia Rodriguez  Desk Drawer Organizer    Furniture         1
33     1034      Alex Johnson            Index Cards   Stationery       100
34     1035     Yuki Yamamoto          Monitor Stand  Electronics         1
35     1036     Emma Thompson     Desk Lamp with USB    Furniture         1
36     1037     Carlos Santos       Wireless Earbuds  Electronics         1
37     1038    Leila Mansouri               Desk Pad    Furniture         1
38     1039        Daniel Kim            Power Strip  Electronics         2
39     1040      Anna Ivanova             Desk Clock    Furniture         1

     Price   OrderDate Shipped       Country
0   1200.0  2024-06-01     Yes           USA
1    150.0  2024-06-03      No        Canada
2    300.0  2024-06-04     Yes           UAE
3     45.0  2024-06-05     Yes     Singapore
4     80.0  2024-06-06      No        Mexico
5      5.0  2024-06-07     Yes           UAE
6    450.0  2024-06-08     Yes            UK
7    220.0  2024-06-09      No   South Korea
8      1.5  2024-06-10     Yes         Italy
9     35.0  2024-06-11     Yes         Japan
10    85.0  2024-06-12     Yes        France
11   180.0  2024-06-13      No         India
12    12.0  2024-06-14     Yes     Australia
13    25.0  2024-06-15     Yes         Spain
14   280.0  2024-06-16      No         China
15     8.0  2024-06-17     Yes         Egypt
16    45.0  2024-06-18     Yes        Poland
17    65.0  2024-06-19      No           USA
18    15.0  2024-06-20     Yes         Japan
19   120.0  2024-06-21     Yes  Saudi Arabia
20     3.5  2024-06-22      No        Canada
21    95.0  2024-06-23     Yes        Brazil
22    35.0  2024-06-24     Yes       Germany
23     4.0  2024-06-25      No      Pakistan
24    28.0  2024-06-26     Yes        Sweden
25    75.0  2024-06-27     Yes        France
26    22.0  2024-06-28      No     Argentina
27     2.5  2024-06-29     Yes        Russia
28   110.0  2024-06-30     Yes   South Korea
29    18.0  2024-07-01      No         Italy
30    32.0  2024-07-02     Yes       Morocco
31   140.0  2024-07-03     Yes       Germany
32    42.0  2024-07-04      No      Colombia
33     0.8  2024-07-05     Yes           USA
34    55.0  2024-07-06     Yes         Japan
35    68.0  2024-07-07      No            UK
36   125.0  2024-07-08     Yes      Portugal
37    28.0  2024-07-09     Yes          Iran
38    18.0  2024-07-10      No   South Korea
39    35.0  2024-07-11     Yes       Ukraine

In [8]:
#To view first 5 rows of the data frame
df.head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

In [9]:
#To view last 5 rows
df.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [10]:
#General info on the data frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       40 non-null     int64
 1   CustomerName  40 non-null     object
 2   Product       40 non-null     object
 3   Category      40 non-null     object
 4   Quantity      40 non-null     int64
 5   Price         40 non-null     float64
 6   OrderDate     40 non-null     object
 7   Shipped       40 non-null     object
 8   Country       40 non-null     object
dtypes: float64(1), int64(2), object(6)
memory usage: 2.9+ KB

In [11]:
#describes the data in the data frame
df.describe()

           OrderID    Quantity        Price
count    40.000000   40.000000    40.000000
mean   1020.500000    5.450000   106.457500
std      11.690452   15.903475   201.091854
min    1001.000000    1.000000     0.800000
25%    1010.750000    1.000000    18.000000
50%    1020.500000    1.000000    43.500000
75%    1030.250000    2.250000   112.500000
max    1040.000000  100.000000  1200.000000

In [14]:
#info on the type of columns
df.columns

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='object')

In [15]:
df.index

RangeIndex(start=0, stop=40, step=1)

In [16]:
#To call out a particular row in the data frame
df["Country"]

0              USA
1           Canada
2              UAE
3        Singapore
4           Mexico
5              UAE
6               UK
7      South Korea
8            Italy
9            Japan
10          France
11           India
12       Australia
13           Spain
14           China
15           Egypt
16          Poland
17             USA
18           Japan
19    Saudi Arabia
20          Canada
21          Brazil
22         Germany
23        Pakistan
24          Sweden
25          France
26       Argentina
27          Russia
28     South Korea
29           Italy
30         Morocco
31         Germany
32        Colombia
33             USA
34           Japan
35              UK
36        Portugal
37            Iran
38     South Korea
39         Ukraine
Name: Country, dtype: object

In [17]:
#shows unique values
set(df["Country"])

{'Argentina',
 'Australia',
 'Brazil',
 'Canada',
 'China',
 'Colombia',
 'Egypt',
 'France',
 'Germany',
 'India',
 'Iran',
 'Italy',
 'Japan',
 'Mexico',
 'Morocco',
 'Pakistan',
 'Poland',
 'Portugal',
 'Russia',
 'Saudi Arabia',
 'Singapore',
 'South Korea',
 'Spain',
 'Sweden',
 'UAE',
 'UK',
 'USA',
 'Ukraine'}

In [18]:
#To see columns side by side
#df[["Country", "Product"]]

         Country                Product
0            USA                 Laptop
1         Canada             Headphones
2            UAE           Office Chair
3      Singapore              Desk Lamp
4         Mexico               Keyboard
5            UAE               Notebook
6             UK          Standing Desk
7    South Korea                Monitor
8          Italy                    Pen
9          Japan                  Mouse
10        France                 Webcam
11         India           File Cabinet
12     Australia                Stapler
13         Spain              USB Drive
14         China              Bookshelf
15         Egypt          Printer Paper
16        Poland         Wireless Mouse
17           USA         Desk Organizer
18         Japan             Calculator
19  Saudi Arabia             Whiteboard
20        Canada           Highlighters
21        Brazil      Bluetooth Speaker
22       Germany           Office Plant
23      Pakistan           Sticky Notes
24        Sweden           Tablet Stand
25        France         Paper Shredder
26     Argentina         Desk Chair Mat
27        Russia           Binder Clips
28   South Korea      Wireless Keyboard
29         Italy          Desk Calendar
30       Morocco                USB Hub
31       Germany       Document Scanner
32      Colombia  Desk Drawer Organizer
33           USA            Index Cards
34         Japan          Monitor Stand
35            UK     Desk Lamp with USB
36      Portugal       Wireless Earbuds
37          Iran               Desk Pad
38   South Korea            Power Strip
39       Ukraine             Desk Clock

In [19]:
#Index based on rows, this shows all the values in the first row i.e index 0
df.iloc[0]

OrderID                1001
CustomerName     John Smith
Product              Laptop
Category        Electronics
Quantity                  1
Price                1200.0
OrderDate        2024-06-01
Shipped                 Yes
Country                 USA
Name: 0, dtype: object

In [20]:
#converts the row indexed at 10 into a list
list(df.iloc[10])

[np.int64(1011),
 'Sophie Martin',
 'Webcam',
 'Electronics',
 np.int64(1),
 np.float64(85.0),
 '2024-06-12',
 'Yes',
 'France']

In [21]:
#directly acess the row value of country
df.iloc[10]["Country"]

'France'

In [23]:
#To filter values that match in the dataframe
df[df["Category"] == "Electronics"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea

In [24]:
#To filter multiple values, This would return only rows where both conditions are true 
df[(df["Category"] == "Electronics") & (df["Country"] == "USA")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA

In [25]:
#It selects rows from the DataFrame df where at least one of two conditions is true.
df[(df["Category"] == "Electronics") | (df["Country"] == "USA")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea

In [27]:
# To check frequency of values
df[df["Quantity"] > 2]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [28]:
df[df["CustomerName"].str.startswith("A")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [29]:
df[df["CustomerName"].str.endswith("a")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [30]:
#To filter based on selected countries
df[df["Country"].isin(["USA", "Sweden", "Brazil"])]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [31]:
#To do a reversal of everything that is not in the selected countries
df[~df["Country"].isin(["USA", "Sweden", "Brazil"])]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [33]:
#Updating Values
df.loc[df["CustomerName"] == "Anna Ivanova", "Product"] = "Burger"

In [35]:
#Product name for customer changed and updated to burger
df.loc[df["CustomerName"] == "Anna Ivanova"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
39,1040,Anna Ivanova,Burger,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [38]:
#Updating USA to United States
df.loc[df["Country"] == "USA", "Country"] = "United States"

In [40]:
df.loc[df["Country"] == "United States"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,United States
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,United States
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,United States

In [41]:
#Transformation from lower to uppercase
df["Country"] = df["Country"].str.upper()

In [42]:
df["Country"]

0     UNITED STATES
1            CANADA
2               UAE
3         SINGAPORE
4            MEXICO
5               UAE
6                UK
7       SOUTH KOREA
8             ITALY
9             JAPAN
10           FRANCE
11            INDIA
12        AUSTRALIA
13            SPAIN
14            CHINA
15            EGYPT
16           POLAND
17    UNITED STATES
18            JAPAN
19     SAUDI ARABIA
20           CANADA
21           BRAZIL
22          GERMANY
23         PAKISTAN
24           SWEDEN
25           FRANCE
26        ARGENTINA
27           RUSSIA
28      SOUTH KOREA
29            ITALY
30          MOROCCO
31          GERMANY
32         COLOMBIA
33    UNITED STATES
34            JAPAN
35               UK
36         PORTUGAL
37             IRAN
38      SOUTH KOREA
39          UKRAINE
Name: Country, dtype: object

In [44]:
#Deleting data, to delete a row
df = df.drop(39)

In [45]:
#This deletes the last row i,e 39
df.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA

In [46]:
#Replace missing or empty values with Zero
df.fillna({"OrderID": 0}, inplace=True)

In [49]:
#Rename Columns
df.rename(columns={"OrderID": "Order ID"}, inplace=True)

In [50]:
df

,Order ID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,UNITED STATES
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,POLAND
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,UNITED STATES
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,COLOMBIA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,UNITED STATES
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA

In [51]:
#To count the number of times a value appears
df["Country"].value_counts()

Country
UNITED STATES    3
SOUTH KOREA      3
JAPAN            3
UK               2
UAE              2
ITALY            2
FRANCE           2
CANADA           2
GERMANY          2
PORTUGAL         1
COLOMBIA         1
BRAZIL           1
MOROCCO          1
RUSSIA           1
ARGENTINA        1
SWEDEN           1
PAKISTAN         1
CHINA            1
SAUDI ARABIA     1
POLAND           1
EGYPT            1
SPAIN            1
AUSTRALIA        1
INDIA            1
MEXICO           1
SINGAPORE        1
IRAN             1
Name: count, dtype: int64

In [52]:
df.groupby("Country")["Price"].sum()

Country
ARGENTINA          22.0
AUSTRALIA          12.0
BRAZIL             95.0
CANADA            153.5
CHINA             280.0
COLOMBIA           42.0
EGYPT               8.0
FRANCE            160.0
GERMANY           175.0
INDIA             180.0
IRAN               28.0
ITALY              19.5
JAPAN             105.0
MEXICO             80.0
MOROCCO            32.0
PAKISTAN            4.0
POLAND             45.0
PORTUGAL          125.0
RUSSIA              2.5
SAUDI ARABIA      120.0
SINGAPORE          45.0
SOUTH KOREA       348.0
SPAIN              25.0
SWEDEN             28.0
UAE               305.0
UK                518.0
UNITED STATES    1265.8
Name: Price, dtype: float64

In [53]:
df.sort_values("Price", ascending=False)

,Order ID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,UNITED STATES
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,UNITED STATES
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,POLAND
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,COLOMBIA
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,UNITED STATES